### ISSUE TITLE
Big ol Ron Strength Bonus

### ISSUE THREAD

**Issue by dde6khkg** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#1]
It seems like the 50% strength bonus in dungeons on the Big ol Ron isn't being applied because I'm getting significantly shorter simulated times in dungeons with the Ragnar Godsword than I am with the Big ol Ron. Is this accurate?

**Comment by gmiclotte** [comment]
Big ol Ron's strength bonus seems to be simulated as intended.
Keep in mind that Big ol Ron only applies it's str bonus to the boss monster in a dungeon, RGS has great stats and a good special attack, so this is not unexpected.

**Comment by dde6khkg** [comment]
Ohhhh. That makes sense. Thanks.
