### ISSUE TITLE
TypeError: prayer.vars is undefined

### ISSUE THREAD

**Issue by alisadah** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#11]
Running Firefox 86 (x64) on Melvor V0.19 and the extension logs this error to console after loading:

```
MICSR: TypeError: prayer.vars is undefined    
    createPrayerSelectCard moz-extension://f8b12a69-1d3f-4fa0-af9d-a409dd5ed7a1/sources/injectable/App.js:651

    createPrayerSelectCard moz-extension://f8b12a69-1d3f-4fa0-af9d-a409dd5ed7a1/sources/injectable/App.js:649

    <anonymous> moz-extension://f8b12a69-1d3f-4fa0-af9d-a409dd5ed7a1/sources/injectable/App.js:213

    onMessage moz-extension://f8b12a69-1d3f-4fa0-af9d-a409dd5ed7a1/sources/injectable/main.js:50
```

Don't know if the prayer object structure has changed, but it looks like it's failing when iterating through prayers returning undefined that don't have a vars child?

**Comment by gmiclotte** [comment]
Hi

This is #4 and it is fixed on the 0.19 branch, so I'm going to close this.

Several things changed under the hood of Melvor Idle in 0.19, and there are still many more issues remaining in the combat simulator. As a result, all the simulations are inaccurate, and this fix won't be put in a new release *yet*.

Thanks for reporting though!
