### ISSUE TITLE
Combat Simulator does not (yet) work in Melvor Idle 0.19

### ISSUE THREAD

**Issue by ACrenshaw** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#12]
Unless I'm missing something, I tried installing installing the zip using Mozilla and chrome and also the plugins from the store with no luck. Am I missing something or are we waiting for an update for the plugin to work again? Looking forward to using again, sorry if this is considered a spam post.

Issue: Plugin not showing in the sidebar list as of the recent update.

**Comment by gmiclotte** [comment]
release v1.3.1 should work in 0.19
