### ISSUE TITLE
Est. Death Rate Doesn't Function Correctly

### ISSUE THREAD

**Issue by GarrettHolly** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#15]
It seems to calculate on some monsters but others it doesn't seem to function correctly. For example when running sim for fire god dungeon if you drop all the way down to 24% dr with 1060 health it says you will still live but that means it will hit you for 988 instead of 1300. Auto eat tier 3 is at 424 hp whales are 480, so after eating one whale would put you above the 80% hp threshold of 848 but only at 904 so still kill range for his magic attack. Could be missing some calculation from agility here but even on rokken who hits for 1235 before reductions seems like something is missing. [Roken](https://i.imgur.com/06MZ0zY.png)

**Comment by gmiclotte** [comment]
This is the auto eat import bug (you can see how it says "manual eating" instead of your auto eat tier), this is fixed in the next release. Thanks for reporting!
