### ISSUE TITLE
Stormsnap fix isn't working

### ISSUE THREAD

**Issue by rolfson32** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#16]
Sim does not seem to account for stormsnap dynamic accuracy/strength when simulating. Using the latest version of the Chrome extension, 1.3.2, the sim uses 0 values for both ranged strength and accuracy when equipping stormsnap. See these two images for comparison:

Stormsnap sim, showing 139.4k xp/hr on cursed maiden: https://i.imgur.com/UdHPCXH.png
Ancient longbow sim, showing 170.6k xp/hr on cursed maiden: https://i.imgur.com/YXT1eBV.png

However if you actually equip those gear sets and go attack a cursed maiden,

Stormsnap has 696 max hit / 78% accuracy : https://i.imgur.com/EI7n2q0.png

Ancient longbow has 587 max hit / 75% accuracy: https://i.imgur.com/IR03NrS.png

I'm not accounting for specials, but stormsnap should be killing considerably faster than ancient longbow does and the sim doesn't reflect it.

**Comment by rolfson32** [comment]
It seems to have something to do with 

https://github.com/visua0/Melvor-Idle-Combat-Simulator-Reloaded/blob/master/Extension/sources/injectable/Simulator.js#L807

lines 807 / 809 not updating the playerStats field, or the combatStats fields getting updated here never filter back into playerStats. Adding debug logs in the sim shows that the simulator here:

https://github.com/visua0/Melvor-Idle-Combat-Simulator-Reloaded/blob/master/Extension/sources/workers/simulator.js#L182

was using the old max hit, obtained before this line is run:

https://github.com/visua0/Melvor-Idle-Combat-Simulator-Reloaded/blob/master/Extension/sources/injectable/Simulator.js#L718

That being said, even forcing player stats to update at the first line doesn't totally fix the sim. That update brings stormsnap roughly in line with ancient longbow even though stormsnap has considerably stronger passive, atk roll, and max hit.

**Comment by gmiclotte** [comment]
Thanks for reporting. So from what I can see, there's a bug with playerStats not getting updated (as you point out), and then there's a bug with slayer area effects. I'll look into fixing that now.

Keep in mind you're using a sandstorm ring which makes DPS comparison a lot more complicated.

**Comment by rolfson32** [comment]
Yeah I didn't attempt to take the sandstorm ring into account as I figured since both sets were using it, it wouldn't affect the relative dps differential between the two. 

I tried to dig into the actual simulator code to see what was happening with the modified max hits and was unable to make much progress. Thanks for looking into it!

**Comment by gmiclotte** [comment]
Turns out the game is actually bugged when the player has access to multiple special attacks. So definitely don't compare in game xp rates with stormsnap+sandstorm ring with what the simulator tells you :upside_down_face: 

Relevant bug report: https://github.com/MelvorIdle/melvoridle.github.io/issues/872

**Comment by gmiclotte** [comment]
Furthermore, it turns out ancient longbow special is broken in the simulation, it dealt 4x damage instead of 2x damage. Getting there ...

**Comment by rolfson32** [comment]
> Turns out the game is actually bugged when the player has access to multiple special attacks. So definitely don't compare in game xp rates with stormsnap+sandstorm ring with what the simulator tells you 🙃
> 
> Relevant bug report: [MelvorIdle/melvoridle.github.io#872](https://github.com/MelvorIdle/melvoridle.github.io/issues/872)

Yup I was only quoting the simulator xp rates, not the game xp rates.

**Comment by gmiclotte** [comment]
New sim results, seems to add up now. Additional logging in the console seems to add up with what I expect too.

![2021-03-19_20-25_1](https://user-images.githubusercontent.com/12995926/111832873-9ef0a900-88f1-11eb-803a-0a82713d8ee1.png)

![2021-03-19_20-25](https://user-images.githubusercontent.com/12995926/111832876-9f893f80-88f1-11eb-8476-300b562cb0a7.png)

Going to wrap this up and release it, thanks for providing this excellent case!

**Comment by rolfson32** [comment]
Great, that looks much more in line with what I was expecting! Curious to dig into the changelog to see exactly what the fix was, had a bit of trouble following all of the stat transformations.

**Comment by gmiclotte** [comment]
Yeah the code is a bit of a mess, I try to improve it bit by bit, but then I make it worse again when I need to add a new Melvor update :upside_down_face:
