### ISSUE TITLE
Kill count calculation seems incorrect in v1.2.4

### ISSUE THREAD

**Issue by tseruga** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#3]
Something doesn't quite seem right with the new update

Here's an example of simulating the same dungeon with 2 sets of gear:

Set 1 - Only a weapon, no armor. Kills/hr is 3.645
![bug1](https://user-images.githubusercontent.com/5778047/105080037-e2e04280-5a55-11eb-808f-25365f32696b.PNG)

Set 2 - A full setup of Aeris. Kills/hr is 2.589
![bug2](https://user-images.githubusercontent.com/5778047/105080044-e4116f80-5a55-11eb-9a2a-b7eed16670dd.PNG)

More damage is done by the Aeris set, yet it gets less kills/hr.

**Comment by gmiclotte** [comment]
Seems like in situation 1 you have a 100% chance of dying, clearly this should result in 0 kills per hour. Until this is fixed you should interpret `kill time` as `time until either the monster or the player died`, and avoid situations where you die.

Thanks for reporting.

**Comment by tseruga** [comment]
Thanks for the info. I saw the patch notes for 1.2.4 and was actually testing the empty set to see what the player dying would look like in the UI. Based on what I saw, and your answer, it seems like this isn't shown to the user? I'm guessing this will change as a result of this bug. Thanks again!

**Comment by gmiclotte** [comment]
It is shown in the `Chance of Death` statistic, which is `1` (100%) in your first screenshot, and `0.0001` (0.01%) in the second. I should probably make that more obvious by colouring these numbers red when non-zero, or something along those lines. Maybe colour code the bars too.

Thanks for the feedback, it is sometimes hard to know what is clear to the user, feedback like this really helps :smiley:

**Comment by gmiclotte** [comment]
Kill count calculation should be fixed in v1.2.5
Kill time is now calculated as `total simulated time / successful kills`.

I've added the colouring of statistics and bars to my todo list, but that will be for a later release.
