### ISSUE TITLE
Calculation error within water god dungeon

### ISSUE THREAD

**Issue by justus-hildebrand** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#31]
Glacia, the water god dungeon boss, has a max hit of 1080 whenever it uses the "Frigid Waves" attack (900dmg) and the player is frozen by its ice break attack (frigid waves damage gets increased by 20%, [see the wiki here](https://wiki.melvoridle.com/w/Glacia))

In my current setup I have 49% DR and am attacking with ranged. With the x1.25 bonus to DR when attacking a magic opponent with ranged, I'd have a DR of 61.25%, meaning the **max hit of Glacia would be 421**.
My character has 1030 HP, which means **the auto-eat threshold is at 412**, so i would not be able to safely idle the dungeon.

Here's the bug: **The damage calculator claims the estimated deathrate to be 0 with these stats**, which according to my maths should not be the case.

Hope this can be fixed easily, else it could cause to some surprising and costly deaths if people are not careful.

**Comment by gmiclotte** [comment]
The wiki is wrong, enemy attacks do not get a stun/sleep multiplier.

**Comment by justus-hildebrand** [comment]
is this a bug in the melvor code base, then? as you can see in the screenshot, its not just the wiki claiming this but also the game itself mentioning the 30% damage increase whenever the player is frozen (highlighted the relevant parts)

![image](https://user-images.githubusercontent.com/9483675/116987541-7a009b80-accf-11eb-98cf-9fcf950d2a32.png)

**Comment by gmiclotte** [comment]
The stun/sleep multipliers were changed to apply to all enemy attacks (somewhere in 0.19 or 0.19.1, idr), instead of only applying to a select few special attacks. As a result, everyone died and complained, until Malcs deliberately disabled the stun/sleep multipliers "temporarily". I assume they'll be activated again in 0.20, but I have no idea.
