### ISSUE TITLE
Suggestion: Enable feature to choose which tier of slayer tasks you are on(and maybe reflect the available monsters based on your slayer level and equipment)

### ISSUE THREAD

**Issue by WobblePotato** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#42]
Not sure if this is the right place to write this, but don't know where else to. I am currently training slayer and thought a feature like this would be really useful, couldn't seem to find one like that. Since slayer tasks have level and equipment requirements, I thought that this simulator would be a great place for all the information to be put together.

**Comment by gmiclotte** [comment]
Hello

This is indeed the right place to put suggestions, although you're also welcome to put them in the #scripting-and-extensions channel in the Melvor Discord server.

Concerning your suggestion, I'm not entirely sure what you mean. Does it relate to the existing auto-slayer simulation category?

**Comment by WobblePotato** [comment]
Not in particular. But because of  the formatting, it's not always very clear which column refers to which monster and which zone it is. Also, an average player (like myself) would not be able to remember by heart what tasks are which category of task. (easy/medium/hard/elite etc). So maybe a grouping based on task category could be nice, or like maybe a dropdown box to select the tier of tasks you're on and it could filter out the ones not available for your task(or your equipment loadout as some zones have equipment requirement)

**Comment by gmiclotte** [comment]
The tasks are grouped by task difficulty here in the auto slayer category, I think that does what you want. If not, feel free to reopen.
![2021-06-29_21-17](https://user-images.githubusercontent.com/12995926/123854902-901d8780-d91f-11eb-8420-303188dd83b3.png)
