### ISSUE TITLE
Single monster/dungeon simulation

### ISSUE THREAD

**Issue by d5c4b3** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#47]
A lot of my use is tweaking a loadout for a particular dungeon or monster to maximize kills, exp, or minimize ammo consumption. In this case re-running the simulation for all the other monsters is unnecessary. 

A refresh/re-run button in the monster details section would be nice.

**Comment by gmiclotte** [comment]
Next version will have a "Simulate Selected" button, which will run a simulation only for the currently selected monster/dungeon/slayer task.

Thanks for the feedback!

**Comment by gmiclotte** [comment]
This is now implemented in v1.4.2.
