### ISSUE TITLE
Add metric for drop or kill rate accounting for rune/ammo crafting

### ISSUE THREAD

**Issue by giewev** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#60]
Sometimes when comparing which enemy is the best to farm, or which spell is best to use, I have two options:
A: Use a large amount of runes per hour, and get a large amount of drops
B: Use a smaller amount of runes per hour, and get a smaller amount of drops

e.g. 
A: use ancient spell and 25k runes/hour, and get 100 kills/hour
B: use an elemental spell and 10k runes/hour, and get 80 kills/hour

It's hard to compare these situations without pulling the numbers out and doing some manual math
If we had the option to provide an approximate time cost for rune crafting, these values could be calculated right in the plugin.

e.g. if we say we can craft 40k runes/hour, then we get adjusted rates of 
A: 100 / (1 + (25 / 40)) = 61.5 kills/hour
B: 80 / (1+ (10 / 40)) = 64 kills/hour

And we get a more clear answer about which is more efficient.
This should be applicable in the same way for bolt/food/prayer usage as well

If you can point me in the right direction I can try to implement a pull request myself.

**Comment by gmiclotte** [comment]
Hello

I'll look into adding this soon, it's been requested many times now.

Regarding the right direction, I'm thinking along these lines:
- [ ] add some input fields in a new tab in the App class, start with a toggle (so we can disable this entirely), and some fields for general food/rune/... gathering time per item, but I'd actually want it to show separate fields for each relevant resource, not all runes or foodstuffs are created at the same rates after all
- [ ] replace the killTimeS property of a sim with a baseKillTimeS (SimManager class), then do the resource math on it to end up at a killTimeS again (in Simulator class or maybe Loot class)
- [ ] make sure dungeons and auto slayer get properly averaged (Simulator class)
- [ ] make sure to correctly recompute other stats that rely on killTimeS 
- [ ] recompute everything when the relevant input fields are changed
- [ ] clearly show in the sim result info card that the results include resource gathering time (App class)

But I'm probably missing some things, and not all the code is as well structured as it should be, so these directions might not make much sense on their own :stuck_out_tongue: but no worries, I'll look into adding it.

**Comment by gmiclotte** [comment]
Implemented this in v1.5.8, let me know if you think it needs some polishing. Thanks !

**Comment by giewev** [comment]
I think that there are some missing input fields for me or something? This is in chrome.

![ResourceRate_Missing_UI](https://user-images.githubusercontent.com/7016741/132050081-581e9008-c31c-4ae3-8961-49554fa1a668.png)

**Comment by gmiclotte** [comment]
By default it only shows the input fields that are relevant for your current setup, so if you enable prayer it should show an input field for prayer points, if you select a spell it should show input fields for runes, etc.

However, with the "Show All Consumables" toggle, you can show all the input fields at once.

**Comment by giewev** [comment]
Oh I see now. I haven't tried to verify the math or anything, but I think it's calculated backwards or something.
When I turn on apply rates the kill time goes down and kills/hr goes up

![Applied_Rates](https://user-images.githubusercontent.com/7016741/132053550-d3818f63-3f3a-4e86-a804-d08fed0aa8f7.png)
![No_Rates](https://user-images.githubusercontent.com/7016741/132053551-0f100973-0495-4e4d-ab09-1a7a230896e5.png)

**Comment by gmiclotte** [comment]
Oh yeah nice catch, looks like kph and kill time were indeed scaling the wrong way, xp/gp/drop rates should be fine though. Should be fixed in 1.5.10, thanks !
