### ISSUE TITLE
GP/hr seems incorrect with signet and infernal stronghold

### ISSUE THREAD

**Issue by Gnuder** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#64]
There seems to be something funky going on with signet and/or infernal stronghold. In the below screenshots I swap my warlock ring out for signet, and my kills per hour on infernal drops by 1, understandably, but the gp/hr is also lower with signet, which seems incorrect as it should be doubling the GP drops from the end of the dungeon (unless my understanding of signet is wrong).

![image](https://user-images.githubusercontent.com/34728280/131752030-490be941-979f-4c27-926d-87238ffb21ae.png)

![image](https://user-images.githubusercontent.com/34728280/131752019-3b6b82f0-4cb3-438c-9663-02596eeb6175.png)

**Comment by gmiclotte** [comment]
Oops, looks like the cash drops are entirely not included, it's only showing the value of the items. Thanks for reporting, I'll fix it later today.

**Comment by gmiclotte** [comment]
Should be fixed in v1.5.8, thanks !
