### ISSUE TITLE
Attack speed in game increased after running simulations

### ISSUE THREAD

**Issue by Gnuder** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#65]
I still need to test this out more to try and figure out what exactly was causing it, but I was running Fire God Dungeon in the game with an Air Imbued Wand and Guardian Amulet which equates to a 2.85s attack interval, casting gust. I was running simulations against the FGD in Combat Sim with other ancient magiks spells and noticed that when I closed the simulator my attack interval in the actual game was now 1.5s, much faster than it should have been. A restart of the game was required to get the attack speed back to normal.

**Comment by gmiclotte** [comment]
Nice catch, thought I found all hidden global references, but apparently not.

Should now be fixed in v1.5.11. Thanks!
