### ISSUE TITLE
incorrect food values

### ISSUE THREAD

**Issue by gmiclotte** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#69]
![2021-10-08_14-10](https://user-images.githubusercontent.com/12995926/136554604-a7a043e2-7998-46d6-ba8b-fd3d8b2eb75c.png)

**Comment by misharp** [comment]
Looks like this is coming from the value calculated by Melvor Idle itself. In the items array, Chicken Soup has a healing value of `11`, where the Perfect Chicken Soup has a healing value of `12.100000000000001`. Just tested and `11 * 1.1` with javascript returns that number... thanks javascript...

@gmiclotte I'd be happy to submit a PR that rounds it where you display it if you think that's an ok fix. Can I create a branch here or should I fork the repo? What branch would you like me to create the PR to?

**Comment by gmiclotte** [comment]
@misharp That'd be great, thanks! Easiest would be if you fork the repo and make a PR to the master branch.

**Comment by gmiclotte** [comment]
fixed in v1.6.1
