### ISSUE TITLE
ReferenceError: showCommas is not defined

### ISSUE THREAD

**Issue by allanw1** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#70]
I'm getting the error: ReferenceError: showCommas is not defined
thousands of times in console when I do a single simulation. This freezes the browser
showCommas is defined and set to "true"

Occasionally I can get this backtrace:
[https://cdn.discordapp.com/attachments/664637399028072470/900562287595757568/unknown.png](https://cdn.discordapp.com/attachments/664637399028072470/900562287595757568/unknown.png)

**Comment by gmiclotte** [comment]
https://media.discordapp.net/attachments/664637399028072470/905263044257529916/unknown.png

**Comment by gmiclotte** [comment]
can't reproduce in the latest version, feel free to reopen if it still happens
