### ISSUE TITLE
Extra stun damage not calculated with 1-handed styles?

### ISSUE THREAD

**Issue by mczubaj** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#74]
Hi, it seems that there's a problem with stun damage calculations (?) with 1 handed styles (or maybe it's about the different attack interval?).
For some reason it's especially apparent with Terran.

1-handed setup - https://i.imgur.com/jXbF3SY.png
Damage reduction = 48%
Highest hit taken = 380

2-handed setup - https://i.imgur.com/VCMdDjH.png
Took off 8% DR shield, put on 8% DR helm.
Damage reduction = 48%
Highest hit taken = 494

I did a "live" test (actually fought Terran) and the 2-handed calculations are correct. One handed are not.
The non-stunned max hit was 380 and 493 while stunned (I think stunned was indeed 1 hp off, but that's neglible).

Tested with melee setups too and the problem occurs too.

What's weird is that other monsters that are able to stun in Earth dungeon are calculated fine for both setups.
What's even weirder is that the problem is not present for Water God and very slightly present for Air God. I didn't do much research for these though, not sure about the possible reason.

**Comment by gmiclotte** [comment]
Thanks for the info. Do you have a settings export for these simulations?

**Comment by mczubaj** [comment]
Hi, sorry for the late reply, not sure why GH didn't consider this worthy of notifying me. :o 

I levelled up a lot since I posted this, but the problem's still around. Note that I didn't update combat sim, not sure if you added any bugfixes recently.

1-handed (incorrect) :
`{
 "version": "v1.6.0-9",
 "course": [
  0,
  5,
  9,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1
 ],
 "courseMastery": {
  "0": false,
  "5": false,
  "9": false,
  "-1": false
 },
 "equipment": [
  630,
  720,
  719,
  721,
  492,
  1143,
  819,
  647,
  722,
  687,
  941,
  -1,
  980,
  994
 ],
 "levels": [
  98,
  102,
  100,
  105,
  97,
  100,
  94,
  90,
  94,
  101,
  81,
  122,
  95,
  93,
  85,
  95,
  102,
  82,
  93,
  111,
  20,
  96,
  78
 ],
 "petUnlocked": [
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  true,
  true,
  true,
  false,
  true,
  false,
  false,
  false,
  true,
  false,
  false,
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  true,
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false
 ],
 "styles": {
  "melee": "Stab",
  "ranged": "Rapid",
  "magic": "Defensive"
 },
 "prayerSelected": [],
 "ancient": -1,
 "aurora": -1,
 "autoEatTier": 2,
 "cookingMastery": false,
 "cookingPool": true,
 "currentGamemode": 0,
 "curse": -1,
 "foodSelected": 1045,
 "healAfterDeath": true,
 "isAncient": false,
 "isManualEating": false,
 "isSlayerTask": false,
 "pillar": -1,
 "potionID": 21,
 "potionTier": 3,
 "standard": 0,
 "summoningSynergy": true,
 "useCombinationRunes": true
}`

2-handed (correct) :
`{
 "version": "v1.6.0-9",
 "course": [
  0,
  5,
  9,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1
 ],
 "courseMastery": {
  "0": false,
  "5": false,
  "9": false,
  "-1": false
 },
 "equipment": [
  718,
  720,
  719,
  721,
  814,
  814,
  819,
  647,
  722,
  687,
  941,
  -1,
  980,
  994
 ],
 "levels": [
  98,
  102,
  100,
  105,
  97,
  100,
  94,
  90,
  94,
  101,
  81,
  122,
  95,
  93,
  85,
  95,
  102,
  82,
  93,
  111,
  20,
  96,
  78
 ],
 "petUnlocked": [
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  true,
  true,
  true,
  false,
  true,
  false,
  false,
  false,
  true,
  false,
  false,
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  true,
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false
 ],
 "styles": {
  "melee": "Stab",
  "ranged": "Rapid",
  "magic": "Defensive"
 },
 "prayerSelected": [],
 "ancient": -1,
 "aurora": -1,
 "autoEatTier": 2,
 "cookingMastery": false,
 "cookingPool": true,
 "currentGamemode": 0,
 "curse": -1,
 "foodSelected": 1045,
 "healAfterDeath": true,
 "isAncient": false,
 "isManualEating": false,
 "isSlayerTask": false,
 "pillar": -1,
 "potionID": 21,
 "potionTier": 3,
 "standard": 0,
 "summoningSynergy": true,
 "useCombinationRunes": true
}`

**Comment by WilTPS** [comment]
If I can add on to this, I was just farming Rokken earlier with the ability to stun.
Was using terran gear similarly, with combat sim indicating 0% death chance. However, the max dmg when I'm stunned is higher than my auto eat threshold..

Not too familiar with settings export or how to assist with this issue. Am using the latest version

**Comment by amulder87** [comment]
This isn't a bug. Cloudburst staff has an attack speed of 3.0, and 3.99 when Terran's grasping roots debuff is applied. Terran has an attack speed of 3.9. If Terran uses grasping roots, then charges to stun, you'll attack too slowly with cloudburst staff to break the stun before Terran's next attack lands. Any weapon faster than 3.0 will always break out of the stun in time, and won't ever take a stunned hit.

**Comment by gmiclotte** [comment]
Sweet, thanks for the information! Going to lock this then.
