### ISSUE TITLE
Debugging?

### ISSUE THREAD

**Issue by deadmann** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#80]
Dear sir,

I'm new to extensions, but I wish to debug the extension and help to improve some issue that bothers me... how can one debug js from extensions?

Firefox state that in inspect we can see js files, but for me it bring a blank list of file when I inspect melvor extension.

(I need to debug to understand data flow of the system)

thank you,
Hassan Faghihi.

**Comment by gmiclotte** [comment]
Hello
No idea, I also ran in the same issue. Because of that, I just add additional logging statements to debug, which works well enough.

Probably better off asking this on a firefox forum or the like, they might be able to help you.

**Comment by deadmann** [comment]
thanks
