### ISSUE TITLE
Prayer XP rate is too high

### ISSUE THREAD

**Issue by hollyroberts** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#81]
In 1.0 prayer XP rates got nerfed significantly, but the simulator is still showing high values. Since it's been a while since the 1.6(.1) release and this isn't a raised issue I figured I'd raise this.

Using rigour as an example., the sim suggests this is 1.4 XP/dmg:

![image](https://user-images.githubusercontent.com/5519754/146085285-b82906a6-8ebe-4406-9af8-fa4e1af3f27c.png)
But the wiki suggests it is much lower:

![image](https://user-images.githubusercontent.com/5519754/146085334-7e20d830-0265-4a1b-8f1e-b4ddbd7b4a81.png)

This falls in line with the simulator suggesting my prayer XP is several times higher than it actually is. I haven't accounted for agility/buffs, because I think it is clear that something hasn't been accounted for. Apologies if this is already a known issue.

**Comment by gmiclotte** [comment]
should be fixed in v1.6.3

Thanks
