### ISSUE TITLE
[Visual Bug] Floating point numbers

### ISSUE THREAD

**Issue by mazunki** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#82]
Floating point numbers are represented as their closest decimal representation. Casting to integer by flooring it would probably solve.

![image](https://user-images.githubusercontent.com/32819373/146533581-2c172c48-aaca-4ca0-91c0-e48fba2b9d76.png)

**Comment by gmiclotte** [comment]
should be fixed in v1.6.3

Thanks
