### ISSUE TITLE
Tier 3 auroras don't work properly even when Book of Eli is equipped

### ISSUE THREAD

**Issue by catharsis71** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#94]
When Book of Eli is equipped, tier 3 auroras still show up as question marks

Manually selecting the relevant question mark seems to enable proper simulation, however, if any gear is changed, the question mark is automatically de-selected

![image](https://user-images.githubusercontent.com/70603733/157710086-f5f1c2ef-e599-4547-991f-8dce9a9e6a2a.png)

Using the import button when a tier 3 aurora is active in the real game will also cause the aurora to be deselected in the simulator

**Comment by gmiclotte** [comment]
Fixed for next release. Thanks!
