### ISSUE TITLE
Importing outfit disables guardian amulet

### ISSUE THREAD

**Issue by mjbartho** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#97]
I died to Rokken when it didn't seem like I should have. With 70% DR, even when I am stunned, Rokken's damage doesn't surpass my autoeat threshold. And yet I died. 

I suspect there may be some weirdness around how the combat simulator imports outfits and the guardian amulet.

Steps I used to reproduce:

- Enter combat
- Observe DR at 70%
- Import outfit
- Observe DR at 63%
- Exit combat
- Observe DR at 51% (combat triangle bonus not active)
- Toggle combat stances
- Observe DR at 56% (combat triangle bonus not active)

In my case, the passive slot had a guardian amulet. I was also able to reproduce this when the guardian amulet was in the neck slot. I haven't done too much testing to see if it's the guardian amulet or the passive slot itself, but this is probably a good amount to fish out the bug with. 

Here is a loom showing the bug https://www.loom.com/share/b37b20ad37a84d0bb30c47d998392ff6

**Comment by gmiclotte** [comment]
Thanks a lot for the detailed steps! Should now be fixed in v1.6.8.

**Comment by mjbartho** [comment]
Sweet, just confirmed I'm no longer seeing this behavior. Really impressive turnaround, thanks!
